### ISSUE TITLE
Randomize the Picnic food and location choice

### ISSUE THREAD

**Issue by Harris-J** [earthiverse/picknic#12]
This was shared on http://www.stupidhackathon.com/ it is an browser app that will choose a random location and order some random food.
Except it isn't contained to the city's wonderful picnic tables...maybe this could be the base of a feature enhancement for picknic? 
https://github.com/chromakode/picnic

**Comment by earthiverse** [comment]
Hahaha, thanks for sharing this! I kept hearing about this from various sources, I really like this concept. I'll share this on social media.

If I have time I'll fork the repo and make it select a random picnic table in the city.
