### ISSUE TITLE
Scripts to grab data

### ISSUE THREAD

**Issue by earthiverse** [earthiverse/picknic#3]
Needs documentation on what to install to get things to work (pymongo + pip for python2.7).
Could potentially update both data in picknic and picknic-dev, instead of just picknic.

workaround: change 'mongo.picknic' to 'mongo["picknic-dev"]' to import data in to the development mongo database.

**Comment by djphan** [comment]
Updated the documentation to reflect the python dependancies. Refer to readme.md for the changes
