### ISSUE TITLE
Search returns incorrect coordinates for some searches

### ISSUE THREAD

**Issue by earthiverse** [earthiverse/picknic#5]
For instance, if you accept the suggestion 'Southgate Transit Centre' you get:
![screenshot from 2016-03-03 17 27 22](https://cloud.githubusercontent.com/assets/602905/13514322/306a63e2-e165-11e5-8816-a022d6dcf6be.png)
Which seems like it's on 'Edmonton, Alberta' instead of 'Southgate Transit Centre'

However, if you just type 'Southgate Transit Centre' without accepting the suggestion you get:
![screenshot from 2016-03-03 17 27 22](https://cloud.githubusercontent.com/assets/602905/13514315/23bf13e0-e165-11e5-93df-a523936ceb3f.png)

**Comment by awwong1** [comment]
The search string is repassed to the google maps api. We probably should get rid of that and use the lat/long provided by the autocomplete.

I think the reason we did this was because we didn't have the auto suggestion, and the suggestion part was added as an afterthought (hack).
